Update main.py
Attempting absolute imports, since for whatever reason I'm getting an error

" from v1.endpoints.users import users
ModuleNotFoundError: No module named 'v1'"